version: "2"
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7.17
    ports:
      - "3306:3306"
  puma:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    environment:
      MYSQL_HOSTNAME: mysql
      MAIL_HOSTNAME: [smtp server]
      MAIL_USERNAME: [username]
      MAIL_PASSWORD: [password]
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./config.ru:/app/config.ru
      - ./db:/app/db
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./lib:/app/lib
      - ./public:/app/public
      - ./Rakefile:/app/Rakefile
      - bundle:/bundle
    depends_on:
      - mysql
volumes:
  bundle:
  node_modules:
